language: php

php:
  - '7.3'
  - '7.4'
  - 'nightly'

env:
  - 'SYMFONY=4.4.0 STABILITY=stable'
  - 'SYMFONY=^4.4 STABILITY=stable'
  - 'SYMFONY=^5.0 STABILITY=stable'
  - 'SYMFONY=^5.1 STABILITY=stable'
  - 'SYMFONY=^5.2 STABILITY=dev'

before_install:
  - composer self-update

install:
  - if [[ "$STABILITY" == "dev" ]]; then composer config minimum-stability dev; fi;
  - if [[ "$(phpenv version-name)" == "nightly" ]]; then export REQS="--ignore-platform-reqs"; fi;
  - composer require --dev  ${REQS} --update-with-all-dependencies
      symfony/http-kernel:${SYMFONY}
      symfony/http-foundation:${SYMFONY}
      symfony/dependency-injection:${SYMFONY}
      symfony/config:${SYMFONY} 
      symfony/twig-bundle:${SYMFONY}
  - composer update ${REQS}

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/psalm
  - vendor/bin/phpunit
  - phpdbg -qrr vendor/bin/infection --min-msi=100

matrix:
  fast_finish: true
  allow_failures:
    - php: 'nightly'
    - env: 'SYMFONY=^5.2 STABILITY=dev'

jobs:
  exclude:
    - php: 'nightly'
      env: 'SYMFONY=4.4.0 STABILITY=stable'
    - php: 'nightly'
      env: 'SYMFONY=^4.4 STABILITY=stable'