language: php

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'
    - php: nightly