language: php

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

env:
  - 'SYMFONY=4.3.0 STABILITY=stable'
  - 'SYMFONY=^4.3.0 STABILITY=stable'
  - 'SYMFONY=^4.4 STABILITY=stable'
  - 'SYMFONY=^5.0 STABILITY=stable'

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source
  - if [[ "$STABILITY" == "dev" ]]; then composer config minimum-stability dev; fi;
  - composer require --dev --update-with-all-dependencies symfony/http-kernel:${SYMFONY} symfony/http-foundation:${SYMFONY} symfony/dependency-injection:${SYMFONY} symfony/config:${SYMFONY} symfony/twig-bundle:${SYMFONY}

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: 'SYMFONY=^5.0 STABILITY=stable'
